### ISSUE TITLE
twitter.com -> x.com

### ISSUE THREAD

**Issue by Kolkman** [lucahammer/tweetXer#10]
The twitter.com domain in the URLs should be replaced by x.com to prevent CORS permission errors

**Comment by mikesafari** [comment]
I just used a Find/Replace in Notepad++ to change anything including "twitter." to "x." (including the periods to skip anything else that matched). That worked for me.

**Comment by lucahammer** [comment]
Fixed by #9 and #12

**Comment by jsnod** [comment]
@lucahammer Thanks for this awesome tool. This still appears to be a problem if you're running from twitter.com. I was able to fix the CORS issues by switching to x.com and it all worked.

**Comment by lucahammer** [comment]
It should now work on both domains.
